import { AdminLayout } from "../layouts";
import {
  OrdersAdmin,
  UsersAdmin,
  CategoriesAdmin,
  ProductsAdmin,
  TablesAdmin,
  TableDetailsAdmin,
} from "../pages/Admin";
import { RouteConfigAdmin } from "../interfaces";

export const routesAdmin: RouteConfigAdmin[] = [
  {
    path: "/admin",
    layout: AdminLayout,
    component: OrdersAdmin,
    icon: "home",
    label: "Pedidos",
    needStaffPermissions: false,
    showInMenu: true,
  },
  {
    path: "/admin/tables",
    layout: AdminLayout,
    component: TablesAdmin,
    icon: "table",
    label: "Mesas",
    needStaffPermissions: false,
    showInMenu: true,
  },
  {
    path: "/admin/payments-history",
    layout: AdminLayout,
    component: OrdersAdmin,
    icon: "history",
    label: "Historial de pagos",
    needStaffPermissions: false,
    showInMenu: true,
  },
  {
    path: "/admin/categories",
    layout: AdminLayout,
    component: CategoriesAdmin,
    icon: "folder",
    label: "Categorias",
    needStaffPermissions: false,
    showInMenu: true,
  },
  {
    path: "/admin/products",
    layout: AdminLayout,
    component: ProductsAdmin,
    icon: "cart",
    label: "Productos",
    needStaffPermissions: false,
    showInMenu: true,
  },
  {
    path: "/admin/users",
    layout: AdminLayout,
    component: UsersAdmin,
    icon: "users",
    label: "Usuarios",
    needStaffPermissions: true,
    showInMenu: true,
  },
  {
    path: "/admin/table/:id",
    layout: AdminLayout,
    component: TableDetailsAdmin,
    icon: "table",
    label: "T",
    needStaffPermissions: false,
    showInMenu: false,
  },
];
